### PR TITLE
Fix pdf generation

### PR DESCRIPTION
**Pull request by nostadt**
At least as per our `sys_file_metadata` table not all PDF files have `width|height` set - sounds legit to me. Therefore they won't be generated at the moment.

We probably want to generate `txt` and whatnot as well. So I would like your input on that matter to find a proper solution.

Oh and with this fix the generated PDF file is invalid, which I consider OK though. At least in the context I am using this faker extension, it is sufficient to see the download button and that it leads to the (invalid) download file.

### CODE REVIEW

**Comment by kitzberger** [comment]
Hi @AMartinNo1, thanks for the MR ;-)

How do you feel about doing it analog to the youtube/vimeo handling? See line 57 and 111. Maybe putting a tiny PDF dummy file into the extension what will be written to the target location just like the Rick Astley video?

**Comment by nostadt** [comment]
> Hi @AMartinNo1, thanks for the MR ;-)
> 
> How do you feel about doing it analog to the youtube/vimeo handling? See line 57 and 111. Maybe putting a tiny PDF dummy file into the extension what will be written to the target location just like the Rick Astley video?

I am not very sure what you mean with analog to youtube/vimeo in that context but from what I understand your goal for PDF is this:

```php
<?php

if ($extension === 'pdf') {
  copy('EXT:sys_filefaker/some_path/Dummy.pdf', $this->publicUrl);
}
```

Of course this code is supposed to be an example to demonstrate the idea.

**Comment by kitzberger** [comment]
Yeah, something like that :-)

I just meant to put the pdf copying next to the block where the YouTube file is being written. If you want I can look into it later or you go ahead and do it right away :-)

**Comment by nostadt** [comment]
> Yeah, something like that :-)
> 
> I just meant to put the pdf copying next to the block where the YouTube file is being written. If you want I can look into it later or you go ahead and do it right away :-)

Ah I see. Not sure if I find time today, so feel free to go ahead later. Tomorrow morning I could test it in my project and provide feedback.

**Comment by kitzberger** [comment]
@AMartinNo1, I've implemented faking vimeo, txt and pdf files. Please have a go ;-)

**Comment by nostadt** [comment]
Let's go with your change 👍🏻 I appreciate your quick response throughout the recent PRs.

Do you find time to make an other release today? 😃

**Comment by kitzberger** [comment]
No biggie ;-)

It's on packagist: https://packagist.org/packages/kitzberger/sysfile-faker#1.6.0
And on TER: https://extensions.typo3.org/extension/sysfile_faker

**Pull request merged**
