### PR TITLE
Add TYPO3 12 compatibility

### PR DESCRIPTION
**Pull request by garbast**

### CODE REVIEW

**Comment by kitzberger** [comment]
@garbast, closed this by accident?

**Comment by evoWeb** [comment]
Yeah it shouldn't be closed. Didn't knew, that i have to keep the repository alive until this one is merged.

Would be great to have the change merged.

**Comment by kitzberger** [comment]
@evoWeb, I failed to checkout the changes from your deleted repo, so I updated it manually again. It's been released as version 2.0.0 and is TYPO3 12 only.

**Comment by evoWeb** [comment]
Thank you so much and sorry to make it unnecessary complicated.

**Pull request closed without merging**
