### PR TITLE
Introduce composer normalize

### PR DESCRIPTION
**Pull request by nostadt**
See https://github.com/TYPO3-Documentation/tea

### CODE REVIEW

**Comment by kitzberger** [comment]
@AMartinNo1, hm, I'd rather not have a binary in the extension. Why not simply fix composer.json without the phar?

**Comment by nostadt** [comment]
> @AMartinNo1, hm, I'd rather not have a binary in the extension. Why not simply fix composer.json without the phar?

In a future step it can be run in the CI.

**Comment by kitzberger** [comment]
> > @AMartinNo1, hm, I'd rather not have a binary in the extension. Why not simply fix composer.json without the phar?
> 
> In a future step it can be run in the CI.

Who's maintaining that file? Why can't it be part of the CI setup? Don't see the benefit here ;-/ Sorry...

**Comment by nostadt** [comment]
> > > @AMartinNo1, hm, I'd rather not have a binary in the extension. Why not simply fix composer.json without the phar?
> > 
> > 
> > In a future step it can be run in the CI.
> 
> Who's maintaining that file? Why can't it be part of the CI setup? Don't see the benefit here ;-/ Sorry...

Cause this way it can be executed locally as well. I get your point with maintaining this file though - you don't want to increase the maintenance work for this extension. What we could do is to require it using composer. This way it gets installed whenever needed and can be upgraded easily as well.

**Comment by nostadt** [comment]
I've updated the PR. So it uses the composer dep now.

**Comment by nostadt** [comment]
Do you consider it when it uses the composer dep or should we close this PR?

**Comment by kitzberger** [comment]
@AMartinNo1, thanks for your efforts. But to be honest I don't think it's a good idea to have such a dependency within this extension. I'm not against changing the indention/formatting of the composer.json in general that why I've just altered that file to your suggestions.

**Comment by nostadt** [comment]
> @AMartinNo1, thanks for your efforts. But to be honest I don't think it's a good idea to have such a dependency within this extension. I'm not against changing the indention/formatting of the composer.json in general that why I've just altered that file to your suggestions.

No problem. That's one thing PR are for IMO, to suggest changes 😊

**Pull request closed without merging**
